### ISSUE TITLE
Add instructions how to re-create basic experiments

### ISSUE THREAD

**Issue by henrykmichalewski** [unixpickle/treeagent#1]
I would like to re-run Pong and Breakout. Can you add some basic instructions how to setup a generic ubuntu box so it will run these experiments?

**Comment by unixpickle** [comment]
Here are the general steps:

 * (Using Python 3) install OpenAI Gym with the Atari extras `pip install gym[atari]`.
 * Run [gym-socket-api](https://github.com/unixpickle/gym-socket-api) in the background.
 * Install Golang
 * Run [train_ppo/main.go](https://github.com/unixpickle/treeagent/blob/master/experiments/train_ppo/main.go)
 * See the arguments to pass in from a training log (e.g. [this one](https://raw.githubusercontent.com/unixpickle/treeagent/master/experiments/train_ppo/logs/Breakout-ram-v0.txt))

With that being said, this repo is fairly messy and unmaintained, and I don't have the exact hyper-parameters that worked the best in the past. Also, I made some major improvements to the algorithm since I made this repo, but the code isn't currently open source since I did it on equipment provided by my employer.

**Comment by henrykmichalewski** [comment]
Thanks. The instructions does work. One upgrade is necessary with respect to the standard ubuntu 16.04. Namely, by default ubuntu will install golang 1.6 and the code seems to depend on some features of golang >= 1.7.
